Loops homework (currrent & past)
fashion-prepod/front13_homework pull request #16
Opened 2022-03-28 20:35 UTC by ExoticDuck

2022-04-01 13:35 UTC, fashion-prepod requested changes

2022-04-01 13:35 UTC, fashion-prepod commented on nikita_marchenkov/loops/main.js
> +    for(let i = age; i<=2022; i++) {
зачем тут отступ ? for  не вложен куда-либо

2022-04-01 13:35 UTC, fashion-prepod commented on nikita_marchenkov/loops/main.js
> +    age++
объявили age2, увеличиваем age

2022-04-01 13:35 UTC, fashion-prepod commented on nikita_marchenkov/loops/main.js
> +for (let i = 0; i < Infinity; i++) {
чтобы цикл был бесконечным достаточно просто убрать условие

2022-04-01 13:35 UTC, fashion-prepod commented on nikita_marchenkov/loops/main.js
> +function SuperSum(n, sum) {
название функций пишется с маленькой буквы

2022-04-01 13:35 UTC, fashion-prepod commented on nikita_marchenkov/loops/main.js
> +for(let i = 0; i < 10000; i++) {
цикл должен быть бесконечным

2022-04-01 13:35 UTC, fashion-prepod commented on nikita_marchenkov/loops/main.js
> +for(let i = 0; i<Infinity ;i++) {
убираем условие цикла

2022-04-02 11:26 UTC, ExoticDuck commented
Все пофиксил, спасибо.

2022-04-02 19:39 UTC, merged