nmarchenkov/arrays
fashion-prepod/front13_homework pull request #29
Opened 2022-04-01 18:52 UTC by ExoticDuck

2022-04-02 19:53 UTC, fashion-prepod requested changes

2022-04-02 19:53 UTC, fashion-prepod commented on nikita_marchenkov/arrays/main.js
> +    (i === 0 || i === 7) ? arrayOfZerosAndOnes[i] = 1 : arrayOfZerosAndOnes[i] = 0;
Нам важно что возвращает тернарный оператор? То что он вернул мы используем?

2022-04-02 19:53 UTC, fashion-prepod commented on nikita_marchenkov/arrays/main.js
> +    zerosAndOnes[i] = i % 2 === 0 ? 0 : 1;
Вот здесь тернарный использован правильно

2022-04-02 19:53 UTC, fashion-prepod commented on nikita_marchenkov/arrays/main.js
> +let Value = 1;
Почему название переменной с большой буквы?

2022-04-02 19:53 UTC, fashion-prepod commented on nikita_marchenkov/arrays/main.js
> +    i < 4 ? num++ : num--;
Тут if

2022-04-03 10:35 UTC, ExoticDuck commented
Исправил, спасибо

2022-05-13 11:57 UTC, merged