Astarosotnikov/arrays
fashion-prepod/front13_homework pull request #30
Opened 2022-04-01 21:19 UTC by Xaky0105

2022-04-02 19:56 UTC, fashion-prepod requested changes

2022-04-02 19:56 UTC, fashion-prepod commented on anton_starosotnikov/arrays/index.js
> +//     arr[i] % 2 === 0 ? evenNum++ : null;
Мы используем то, что возвращает тернарник? Переписать в if

2022-04-02 19:56 UTC, fashion-prepod commented on anton_starosotnikov/arrays/index.js
> +let num = arr[0];
maxNumber а не num

2022-04-04 20:59 UTC, Xaky0105 commented
Домашку по массивам исправил. Но случайно запушил в эту же ветку домашку по методам массива

2022-04-22 12:02 UTC, merged