Agorbunova/array methods
fashion-prepod/front13_homework pull request #45
Opened 2022-04-08 09:28 UTC by GorbunovaAnna

2022-04-22 12:12 UTC, fashion-prepod requested changes

2022-04-22 12:12 UTC, fashion-prepod commented on Anna_Gorbunova/arrayMethods/index.js
> +//     if (userName === people1[i]) {
.indexOf()

2022-04-22 12:12 UTC, fashion-prepod commented on Anna_Gorbunova/arrayMethods/index.js
> +//     if (people2.includes(people1[i])) {
```
if ( !people2.includes(people1[i]) ) {
  newArr.push(people1[i]);
}
```

2022-04-25 14:43 UTC, GorbunovaAnna commented on Anna_Gorbunova/arrayMethods/index.js
> +//     if (userName === people1[i]) {
fixed

2022-04-25 14:43 UTC, GorbunovaAnna commented on Anna_Gorbunova/arrayMethods/index.js
> +//     if (people2.includes(people1[i])) {
fixed

2022-05-13 12:43 UTC, merged